Config.IgnoreClasses = {
    [13] = true, -- Cycles
    [14] = true, -- Boats
    [15] = true, -- Helicopters
    [16] = true, -- Planes
    [21] = true, -- Trains
}

Config.WheelBones = {
    [0] = 'wheel_lf',
    [1] = 'wheel_rf',
    [2] = 'wheel_lm',
    [3] = 'wheel_rm',
    [4] = 'wheel_lr',
    [5] = 'wheel_rr',
    --[45] = '',
    --[46] = ''
}

Config.HornLabels = {
    [0] = 'Truck Horn',
    [1] = 'Cop Horn',
    [2] = 'Clown Horn',
    [3] = 'Musical Horn 1',
    [4] = 'Musical Horn 2',
    [5] = 'Musical Horn 3',
    [6] = 'Musical Horn 4',
    [7] = 'Musical Horn 5',
    [8] = 'Sad Trombone',
    [9] = 'Classical Horn 1',
    [10] = 'Classical Horn 2',
    [11] = 'Classical Horn 3',
    [12] = 'Classical Horn 4',
    [13] = 'Classical Horn 5',
    [14] = 'Classical Horn 6',
    [15] = 'Classical Horn 7',
    [16] = 'Scale - Do',
    [17] = 'Scale - Re',
    [18] = 'Scale - Mi',
    [19] = 'Scale - Fa',
    [20] = 'Scale - Sol',
    [21] = 'Scale - La',
    [22] = 'Scale - Ti',
    [23] = 'Scale - Do',
    [24] = 'Jazz Horn 1',
    [25] = 'Jazz Horn 2',
    [26] = 'Jazz Horn 3',
    [27] = 'Jazz Horn Loop',
    [28] = 'Star Spangled Banner 1',
    [29] = 'Star Spangled Banner 2',
    [30] = 'Star Spangled Banner 3',
    [31] = 'Star Spangled Banner 4',
    [32] = 'Classical Horn 8 Loop',
    [33] = 'Classical Horn 9 Loop',
    [34] = 'Classical Horn 10 Loop',
    [35] = 'Classical Horn 8',
    [36] = 'Classical Horn 9',
    [37] = 'Classical Horn 10',
    [38] = 'Funeral Loop',
    [39] = 'Funeral',
    [40] = 'Spooky Loop',
    [41] = 'Spooky',
    [42] = 'San Andreas Loop',
    [43] = 'San Andreas',
    [44] = 'Liberty City Loop',
    [45] = 'Liberty City',
    [46] = 'Festive 1 Loop',
    [47] = 'Festive 1',
    [48] = 'Festive 2 Loop',
    [49] = 'Festive 2',
    [50] = 'Festive 3 Loop',
    [51] = 'Festive 3'
}

-- https://docs.fivem.net/natives/?_0xB3ED1BFB4BE636DC
Config.WheelCategories = {
    { label = 'Sport',              id = 0 },
    { label = 'Muscle',             id = 1 },
    { label = 'Lowrider',           id = 2 },
    { label = 'SUV',                id = 3 },
    { label = 'Offroad',            id = 4 },
    { label = 'Tuner',              id = 5 },
    { label = 'Motorcycle',         id = 6 },
    { label = 'High End',           id = 7 },
    { label = 'Benny\'s Originals', id = 8 },
    { label = 'Benny\'s Bespoke',   id = 9 },
    { label = 'Open Wheel',         id = 10 },
    { label = 'Street',             id = 11 },
    { label = 'Track',              id = 12 },
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.InteriorCategories = {
    { label = 'Roll Cage',      id = 5 },
    { label = 'Horns',          id = 14 },
    { label = 'Subwoofer',      id = 19 },
    { label = 'Dashboard',      id = 29 },
    { label = 'Dial',           id = 30 },
    { label = 'Door Speaker',   id = 31 },
    { label = 'Seats',          id = 32 },
    { label = 'Steering Wheel', id = 33 },
    { label = 'Shifter Leaver', id = 34 },
    { label = 'Plaque',         id = 35 },
    { label = 'Speaker',        id = 36 },
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.ExteriorCategories = {
    { label = 'Spoiler',       id = 0 },
    { label = 'Front Bumper',  id = 1 },
    { label = 'Rear Bumper',   id = 2 },
    { label = 'Side Skirt',    id = 3 },
    { label = 'Exhaust',       id = 4 },
    { label = 'Grille',        id = 6 },
    { label = 'Hood',          id = 7 },
    { label = 'Left Fender',   id = 8 },
    { label = 'Right Fender',  id = 9 },
    { label = 'Roof',          id = 10 },
    { label = 'Hydraulics',    id = 21 },
    { label = 'Headlights',    id = 22 },
    { label = 'Tire Smoke',    id = 20 },
    { label = 'Rear Wheels',   id = 24 },
    { label = 'Plate Holder',  id = 25 },
    { label = 'Vanity Plates', id = 26 },
    { label = 'Trim A',        id = 27 },
    { label = 'Ornaments',     id = 28 },
    { label = 'Trunk',         id = 37 },
    { label = 'Hydraulic',     id = 38 },
    { label = 'Engine Block',  id = 39 },
    { label = 'Air Filter',    id = 40 },
    { label = 'Strut',         id = 41 },
    { label = 'Arch Cover',    id = 42 },
    { label = 'Aerial',        id = 43 },
    { label = 'Trim B',        id = 44 },
    { label = 'Fuel Tank',     id = 45 },
    { label = 'Window',        id = 46 },
    { label = 'Door',          id = 47 },
    { label = 'Livery',        id = 48 },
    { label = 'Lightbar',      id = 49 },
    { label = 'Paint',         id = 50 }
}

-- https://docs.fivem.net/natives/?_0x3DFF319A831E0CDB
Config.Xenon = {
    { label = 'Default',       id = -1 },
    { label = 'White',         id = 0 },
    { label = 'Blue',          id = 1 },
    { label = 'Electric Blue', id = 2 },
    { label = 'Mint Green',    id = 3 },
    { label = 'Lime Green',    id = 4 },
    { label = 'Yellow',        id = 5 },
    { label = 'Golden Shower', id = 6 },
    { label = 'Orange',        id = 7 },
    { label = 'Red',           id = 8 },
    { label = 'Pony Pink',     id = 9 },
    { label = 'Hot Pink',      id = 10 },
    { label = 'Purple',        id = 11 },
    { label = 'Blacklight',    id = 12 },
}

-- https://docs.fivem.net/natives/?_0x57C51E6BAD752696
Config.WindowTints = {
    { label = 'None',        id = 0 },
    { label = 'Pure black',  id = 1 },
    { label = 'Dark Smoke',  id = 2 },
    { label = 'Light Smoke', id = 3 },
    { label = 'Stock',       id = 4 },
    { label = 'Limo',        id = 5 },
    { label = 'Green',       id = 6 },
}

-- https://docs.fivem.net/natives/?_0x9088EB5A43FFB0A1
Config.PlateIndexes = {
    { label = 'Blue on White 1', id = 0 },
    { label = 'Yellow on Black', id = 1 },
    { label = 'Yellow on Blue',  id = 2 },
    { label = 'Blue on White 2', id = 3 },
    { label = 'Blue on White 3', id = 4 },
    { label = 'Yankton',         id = 5 },
    { label = 'Ecola',           id = 6 },
    { label = 'Las Venturas',    id = 7 },
    { label = 'Liberty City',    id = 8 },
    { label = 'LS Car Meet',     id = 9 },
    { label = 'Panic',           id = 10 },
    { label = 'Pounders',        id = 11 },
    { label = 'Sprunk',          id = 12 },
}

-- https://docs.fivem.net/natives/?_0x2AA720E4287BF269
Config.Neon = {
    { label = 'Left',  id = 0 },
    { label = 'Right', id = 1 },
    { label = 'Front', id = 2 },
    { label = 'Back',  id = 3 },
}

-- https://docs.fivem.net/natives/?_0x8E0A582209A62695
Config.NeonColors = {
    { label = 'White',         r = 222, g = 222, b = 255 },
    { label = 'Blue',          r = 2,   g = 21,  b = 255 },
    { label = 'Electric Blue', r = 3,   g = 83,  b = 255 },
    { label = 'Mint Green',    r = 0,   g = 255, b = 140 },
    { label = 'Lime Green',    r = 94,  g = 255, b = 1 },
    { label = 'Yellow',        r = 255, g = 255, b = 0 },
    { label = 'Golden Shower', r = 255, g = 150, b = 0 },
    { label = 'Orange',        r = 255, g = 62,  b = 0 },
    { label = 'Red',           r = 255, g = 1,   b = 1 },
    { label = 'Pony Pink',     r = 255, g = 50,  b = 100 },
    { label = 'Hot Pink',      r = 255, g = 5,   b = 190 },
    { label = 'Purple',        r = 35,  g = 1,   b = 255 },
    { label = 'Blacklight',    r = 15,  g = 3,   b = 255 },
}

-- https://docs.fivem.net/natives/?_0xB5BA80F839791C0F
Config.TyreSmoke = {
    { label = 'White Smoke',  r = 254, g = 254, b = 254 },
    { label = 'Black Smoke',  r = 1,   g = 1,   b = 1 },
    { label = 'Blue Smoke',   r = 0,   g = 150, b = 255 },
    { label = 'Yellow Smoke', r = 255, g = 255, b = 50 },
    { label = 'Orange Smoke', r = 255, g = 153, b = 51 },
    { label = 'Red Smoke',    r = 255, g = 10,  b = 10 },
    { label = 'Green Smoke',  r = 10,  g = 255, b = 10 },
    { label = 'Purple Smoke', r = 153, g = 10,  b = 153 },
    { label = 'Pink Smoke',   r = 255, g = 102, b = 178 },
    { label = 'Gray Smoke',   r = 128, g = 128, b = 128 }
}

Config.Paints = {

    Metallic = {
        { label = 'Metallic Black',               id = 0,   hex = '0d1116' },
        { label = 'Metallic Graphite Black',      id = 1,   hex = '1c1d21' },
        { label = 'Metallic Black Steal',         id = 2,   hex = '32383d' },
        { label = 'Metallic Dark Silver',         id = 3,   hex = '454b4f' },
        { label = 'Metallic Silver',              id = 4,   hex = '999da0' },
        { label = 'Metallic Blue Silver',         id = 5,   hex = 'c2c4c6' },
        { label = 'Metallic Steel Gray',          id = 6,   hex = '979a97' },
        { label = 'Metallic Shadow Silver',       id = 7,   hex = '637380' },
        { label = 'Metallic Stone Silver',        id = 8,   hex = '63625c' },
        { label = 'Metallic Midnight Silver',     id = 9,   hex = '3c3f47' },
        { label = 'Metallic Gun Metal',           id = 10,  hex = '444e54' },
        { label = 'Metallic Anthracite Grey',     id = 11,  hex = '1d2129' },
        { label = 'Metallic Red',                 id = 27,  hex = 'c00e1a' },
        { label = 'Metallic Torino Red',          id = 28,  hex = 'da1918' },
        { label = 'Metallic Formula Red',         id = 29,  hex = 'b6111b' },
        { label = 'Metallic Blaze Red',           id = 30,  hex = 'a51e23' },
        { label = 'Metallic Graceful Red',        id = 31,  hex = '7b1a22' },
        { label = 'Metallic Garnet Red',          id = 32,  hex = '8e1b1f' },
        { label = 'Metallic Desert Red',          id = 33,  hex = '6f1818' },
        { label = 'Metallic Cabernet Red',        id = 34,  hex = '49111d' },
        { label = 'Metallic Candy Red',           id = 35,  hex = 'b60f25' },
        { label = 'Metallic Sunrise Orange',      id = 36,  hex = 'd44a17' },
        { label = 'Metallic Classic Gold',        id = 37,  hex = 'c2944f' },
        { label = 'Metallic Orange',              id = 38,  hex = 'f78616' },
        { label = 'Metallic Dark Green',          id = 49,  hex = '132428' },
        { label = 'Metallic Racing Green',        id = 50,  hex = '122e2b' },
        { label = 'Metallic Sea Green',           id = 51,  hex = '12383c' },
        { label = 'Metallic Olive Green',         id = 52,  hex = '31423f' },
        { label = 'Metallic Green',               id = 53,  hex = '155c2d' },
        { label = 'Metallic Gasoline Blue Green', id = 54,  hex = '1b6770' },
        { label = 'Metallic Midnight Blue',       id = 61,  hex = '222e46' },
        { label = 'Metallic Dark Blue',           id = 62,  hex = '233155' },
        { label = 'Metallic Saxony Blue',         id = 63,  hex = '304c7e' },
        { label = 'Metallic Blue',                id = 64,  hex = '47578f' },
        { label = 'Metallic Mariner Blue',        id = 65,  hex = '637ba7' },
        { label = 'Metallic Harbor Blue',         id = 66,  hex = '394762' },
        { label = 'Metallic Diamond Blue',        id = 67,  hex = 'd6e7f1' },
        { label = 'Metallic Surf Blue',           id = 68,  hex = '76afbe' },
        { label = 'Metallic Nautical Blue',       id = 69,  hex = '345e72' },
        { label = 'Metallic Bright Blue',         id = 70,  hex = '0b9cf1' },
        { label = 'Metallic Purple Blue',         id = 71,  hex = '2f2d52' },
        { label = 'Metallic Spinnaker Blue',      id = 72,  hex = '282c4d' },
        { label = 'Metallic Ultra Blue',          id = 73,  hex = '2354a1' },
        { label = 'Metallic Bright Blue',         id = 74,  hex = '6ea3c6' },
        { label = 'Metallic Taxi Yellow',         id = 88,  hex = 'ffcf20' },
        { label = 'Metallic Race Yellow',         id = 89,  hex = 'fbe212' },
        { label = 'Metallic Bronze',              id = 90,  hex = '916532' },
        { label = 'Metallic Yellow Bird',         id = 91,  hex = 'e0e13d' },
        { label = 'Metallic Lime',                id = 92,  hex = '98d223' },
        { label = 'Metallic Champagne',           id = 93,  hex = '9b8c78' },
        { label = 'Metallic Pueblo Beige',        id = 94,  hex = '503218' },
        { label = 'Metallic Dark Ivory',          id = 95,  hex = '473f2b' },
        { label = 'Metallic Choco Brown',         id = 96,  hex = '221b19' },
        { label = 'Metallic Golden Brown',        id = 97,  hex = '653f23' },
        { label = 'Metallic Light Brown',         id = 98,  hex = '775c3e' },
        { label = 'Metallic Straw Beige',         id = 99,  hex = 'ac9975' },
        { label = 'Metallic Moss Brown',          id = 100, hex = '6c6b4b' },
        { label = 'Metallic Biston Brown',        id = 101, hex = '402e2b' },
        { label = 'Metallic Beechwood',           id = 102, hex = 'a4965f' },
        { label = 'Metallic Dark Beechwood',      id = 103, hex = '46231a' },
        { label = 'Metallic Choco Orange',        id = 104, hex = '752b19' },
        { label = 'Metallic Beach Sand',          id = 105, hex = 'bfae7b' },
        { label = 'Metallic Sun Bleeched Sand',   id = 106, hex = 'dfd5b2' },
        { label = 'Metallic Cream',               id = 107, hex = 'f7edd5' },
        { label = 'Metallic White',               id = 111, hex = 'fffff6' },
        { label = 'Metallic Frost White',         id = 112, hex = 'eaeaea' },
        { label = 'Metallic Securicor Green',     id = 125, hex = '83c566' },
        { label = 'Metallic Vermillion Pink',     id = 137, hex = 'df5891' },
        { label = 'Metallic Black Blue',          id = 141, hex = '0a0c17' },
        { label = 'Metallic Black Purple',        id = 142, hex = '0c0d18' },
        { label = 'Metallic Black Red',           id = 143, hex = '0e0d14' },
        { label = 'Metallic Purple',              id = 145, hex = '621276' },
        { label = 'Metallic V Dark Blue',         id = 146, hex = '0b1421' },
        { label = 'Metallic Lava Red',            id = 150, hex = 'bc1917' },
    },

    Matte = {
        { label = 'Matte Black',         id = 12,  hex = '13181f' },
        { label = 'Matte Gray',          id = 13,  hex = '26282a' },
        { label = 'Matte Light Grey',    id = 14,  hex = '515554' },
        { label = 'Matte Red',           id = 39,  hex = 'cf1f21' },
        { label = 'Matte Dark Red',      id = 40,  hex = '732021' },
        { label = 'Matte Orange',        id = 41,  hex = 'f27d20' },
        { label = 'Matte Yellow',        id = 42,  hex = 'ffc91f' },
        { label = 'Matte Lime Green',    id = 55,  hex = '66b81f' },
        { label = 'Matte Dark Blue',     id = 82,  hex = '1f2852' },
        { label = 'Matte Blue',          id = 83,  hex = '253aa7' },
        { label = 'Matte Midnight Blue', id = 84,  hex = '1c3551' },
        { label = 'Matte Green',         id = 128, hex = '4e6443' },
        { label = 'Matte Brown',         id = 129, hex = 'bcac8f' },
        { label = 'Matte White',         id = 131, hex = 'fcf9f1' },
        { label = 'Matte Purple',        id = 148, hex = '6b1f7b' },
        { label = 'Matte Dark Purple',   id = 149, hex = '1e1d22' },
        { label = 'Matte Forest Green',  id = 151, hex = '2d362a' },
        { label = 'Matte Olive Drab',    id = 152, hex = '696748' },
        { label = 'Matte Desert Brown',  id = 153, hex = '7a6c55' },
        { label = 'Matte Desert Tan',    id = 154, hex = 'c3b492' },
        { label = 'Matte Foilage Green', id = 155, hex = '5a6352' },
    },

    Util = {
        { label = 'Util Black',          id = 15,  hex = '151921' },
        { label = 'Util Black Poly',     id = 16,  hex = '1e2429' },
        { label = 'Util Dark Silver',    id = 17,  hex = '333a3c' },
        { label = 'Util Silver',         id = 18,  hex = '8c9095' },
        { label = 'Util Gun Metal',      id = 19,  hex = '39434d' },
        { label = 'Util Shadow Silver',  id = 20,  hex = '506272' },
        { label = 'Util Red',            id = 43,  hex = '9c1016' },
        { label = 'Util Bright Red',     id = 44,  hex = 'de0f18' },
        { label = 'Util Garnet Red',     id = 45,  hex = '8f1e17' },
        { label = 'Util Dark Green',     id = 56,  hex = '22383e' },
        { label = 'Util Green',          id = 57,  hex = '1d5a3f' },
        { label = 'Util Dark Blue',      id = 75,  hex = '112552' },
        { label = 'Util Midnight Blue',  id = 76,  hex = '1b203e' },
        { label = 'Util Blue',           id = 77,  hex = '275190' },
        { label = 'Util Sea Foam Blue',  id = 78,  hex = '608592' },
        { label = 'Util Lightning Blue', id = 79,  hex = '2446a8' },
        { label = 'Util Maui Blue Poly', id = 80,  hex = '4271e1' },
        { label = 'Util Bright Blue',    id = 81,  hex = '3b39e0' },
        { label = 'Util Brown',          id = 108, hex = '3a2a1b' },
        { label = 'Util Medium Brown',   id = 109, hex = '785f33' },
        { label = 'Util Light Brown',    id = 110, hex = 'b5a079' },
        { label = 'Util Off White',      id = 122, hex = 'dfddd0' },
    },

    Worn = {
        { label = 'Worn Black',            id = 21,  hex = '1e232f' },
        { label = 'Worn Graphite',         id = 22,  hex = '363a3f' },
        { label = 'Worn Silver Grey',      id = 23,  hex = 'a0a199' },
        { label = 'Worn Silver',           id = 24,  hex = 'd3d3d3' },
        { label = 'Worn Blue Silver',      id = 25,  hex = 'b7bfca' },
        { label = 'Worn Shadow Silver',    id = 26,  hex = '778794' },
        { label = 'Worn Red',              id = 46,  hex = 'a94744' },
        { label = 'Worn Golden Red',       id = 47,  hex = 'b16c51' },
        { label = 'Worn Dark Red',         id = 48,  hex = '371c25' },
        { label = 'Worn Dark Green',       id = 58,  hex = '2d423f' },
        { label = 'Worn Green',            id = 59,  hex = '45594b' },
        { label = 'Worn Sea Wash',         id = 60,  hex = '65867f' },
        { label = 'Worn Dark Blue',        id = 85,  hex = '4c5f81' },
        { label = 'Worn Blue',             id = 86,  hex = '58688e' },
        { label = 'Worn Light Blue',       id = 87,  hex = '74b5d8' },
        { label = 'Worn Honey Beige',      id = 113, hex = 'b0ab94' },
        { label = 'Worn Brown',            id = 114, hex = '453831' },
        { label = 'Worn Dark Brown',       id = 115, hex = '2a282b' },
        { label = 'Worn Straw Beige',      id = 116, hex = '726c57' },
        { label = 'Worn Off White',        id = 121, hex = 'eae6de' },
        { label = 'Worn Orange',           id = 123, hex = 'f2ad2e' },
        { label = 'Worn Light Orange',     id = 124, hex = 'f9a458' },
        { label = 'Worn Taxi Yellow',      id = 126, hex = 'f1cc40' },
        { label = 'Worn Orange',           id = 130, hex = 'f8b658' },
        { label = 'Worn White',            id = 132, hex = 'fffffb' },
        { label = 'Worn Olive Army Green', id = 133, hex = '81844c' },
    },

    Misc = {
        { label = 'Brushed Steel',       id = 117, hex = '6a747c' },
        { label = 'Brushed Black Steel', id = 118, hex = '354158' },
        { label = 'Brushed Aluminium',   id = 119, hex = '9ba0a8' },
        { label = 'Chrome',              id = 120, hex = '5870a1' },
        { label = 'Police Car Blue',     id = 127, hex = '4cc3da' },
        { label = 'Pure White',          id = 134, hex = 'ffffff' },
        { label = 'Hot Pink',            id = 135, hex = 'f21f99' },
        { label = 'Salmon Pink',         id = 136, hex = 'fdd6cd' },
        { label = 'Orange',              id = 138, hex = 'f6ae20' },
        { label = 'Green',               id = 139, hex = 'b0ee6e' },
        { label = 'Blue',                id = 140, hex = '08e9fa' },
        { label = 'Hunter Green',        id = 144, hex = '9f9e8a' },
        { label = 'Mod Shop Black',      id = 147, hex = '11141a' },
        { label = 'Alloy',               id = 156, hex = '81827f' },
        { label = 'Epsilon Blue',        id = 157, hex = 'afd6e4' },
        { label = 'Pure Gold',           id = 158, hex = '7a6440' },
        { label = 'Brushed Gold',        id = 159, hex = '7f6a48' }
    },

    Chameleon = {
        { label = 'Anodized Red',           id = 161, hex = 'CF1020' },
        { label = 'Anodized Wine',          id = 162, hex = '5E1224' },
        { label = 'Anodized Purple',        id = 163, hex = '800080' },
        { label = 'Anodized Blue',          id = 164, hex = '0000FF' },
        { label = 'Anodized Green',         id = 165, hex = '008000' },
        { label = 'Anodized Lime',          id = 166, hex = 'AFFF00' },
        { label = 'Anodized Copper',        id = 167, hex = 'B87333' },
        { label = 'Anodized Bronze',        id = 168, hex = 'CD7F32' },
        { label = 'Anodized Champagne',     id = 169, hex = 'F7E7CE' },
        { label = 'Anodized Gold',          id = 170, hex = 'FFD700' },
        { label = 'Green Blue Flip',        id = 171, hex = '1164B4' },
        { label = 'Green Red Flip',         id = 172, hex = 'B43104' },
        { label = 'Green Brown Flip',       id = 173, hex = '735C12' },
        { label = 'Green Turquoise Flip',   id = 174, hex = '43C6DB' },
        { label = 'Green Purple Flip',      id = 175, hex = '9D00FF' },
        { label = 'Teal Purple Flip',       id = 176, hex = '6A0DAD' },
        { label = 'Turquoise Red Flip',     id = 177, hex = 'E60026' },
        { label = 'Turquoise Purple Flip',  id = 178, hex = '30D5C8' },
        { label = 'Cyan Purple Flip',       id = 179, hex = '0FF0FC' },
        { label = 'Blue Pink Flip',         id = 180, hex = '4C2882' },
        { label = 'Blue Green Flip',        id = 181, hex = '138808' },
        { label = 'Purple Red Flip',        id = 182, hex = '9B111E' },
        { label = 'Purple Green Flip',      id = 183, hex = '6B2E53' },
        { label = 'Magenta Green Flip',     id = 184, hex = 'CA1F7B' },
        { label = 'Magenta Yellow Flip',    id = 185, hex = 'FEDF00' },
        { label = 'Burgundy Green Flip',    id = 186, hex = '900020' },
        { label = 'Magenta Cyan Flip',      id = 187, hex = '00FFA1' },
        { label = 'Copper Purple Flip',     id = 188, hex = 'B87333' },
        { label = 'Magenta Orange Flip',    id = 189, hex = 'FF5F1F' },
        { label = 'Red Orange Flip',        id = 190, hex = 'FF4500' },
        { label = 'Orange Purple Flip',     id = 191, hex = 'B04080' },
        { label = 'Orange Blue Flip',       id = 192, hex = '0047AB' },
        { label = 'White Purple Flip',      id = 193, hex = 'F8F0E3' },
        { label = 'Red Rainbow Flip',       id = 194, hex = 'ED2939' },
        { label = 'Blue Rainbow Flip',      id = 195, hex = '4B0082' },
        { label = 'Dark Green Pearl',       id = 196, hex = '013220' },
        { label = 'Dark Teal Pearl',        id = 197, hex = '008080' },
        { label = 'Dark Blue Pearl',        id = 198, hex = '000080' },
        { label = 'Dark Purple Pearl',      id = 199, hex = '301934' },
        { label = 'Oil Slick Pearl',        id = 200, hex = '4B0082' },
        { label = 'Light Green Pearl',      id = 201, hex = '99E550' },
        { label = 'Light Blue Pearl',       id = 202, hex = 'ADD8E6' },
        { label = 'Light Purple Pearl',     id = 203, hex = '967BB6' },
        { label = 'Light Pink Pearl',       id = 203, hex = 'FFB6C1' },
        { label = 'Off White Pearl',        id = 204, hex = 'F2F0E6' },
        { label = 'Pink Pearl',             id = 205, hex = 'EAADEA' },
        { label = 'Yellow Pearl',           id = 206, hex = 'FFF000' },
        { label = 'Green Pearl',            id = 207, hex = '00A550' },
        { label = 'Blue Pearl',             id = 208, hex = '0000FF' },
        { label = 'Cream Pearl',            id = 209, hex = 'FFFDD0' },
        { label = 'White Prismatic',        id = 210, hex = 'FFFFFF' },
        { label = 'Graphite Prismatic',     id = 211, hex = '251607' },
        { label = 'Dark Blue Prismatic',    id = 212, hex = '00008B' },
        { label = 'Dark Purple Prismatic',  id = 213, hex = '301934' },
        { label = 'Hot Pink Prismatic',     id = 214, hex = 'FF69B4' },
        { label = 'Dark Red Prismatic',     id = 215, hex = '8B0000' },
        { label = 'Dark GREEN Prismatic',   id = 216, hex = '013220' },
        { label = 'Black Prismatic',        id = 217, hex = '000000' },
        { label = 'Black Oil Spill',        id = 218, hex = '121212' },
        { label = 'Black Rainbow',          id = 219, hex = '000000' },
        { label = 'Prismatic',              id = 220, hex = 'CCCCCC' },
        { label = 'Black Holographic',      id = 221, hex = '101010' },
        { label = 'White Holographic',      id = 222, hex = 'E6E8FA' },
        { label = 'Monochrome',             id = 223, hex = 'B4B4B4' },
        { label = 'Night & Day',            id = 224, hex = '333366' },
        { label = 'The Verlierer',          id = 225, hex = '550055' },
        { label = 'Sprunk Extreme',         id = 226, hex = '00FF00' },
        { label = 'Vice City',              id = 227, hex = 'FF00FF' },
        { label = 'Synthwave Nights',       id = 228, hex = 'FF007F' },
        { label = 'Four Seasons',           id = 229, hex = '73C2FB' },
        { label = 'Maisonette 9 Throwback', id = 230, hex = 'DCDCDC' },
        { label = 'Bubblegum',              id = 231, hex = 'FFC0CB' },
        { label = 'Full Rainbow',           id = 232, hex = 'FF0000' },
        { label = 'Sunset',                 id = 233, hex = 'FFD700' },
        { label = 'The Seven',              id = 234, hex = '701C1C' },
        { label = 'Kamen Rider',            id = 235, hex = '1C1C70' },
        { label = 'Chromatic Aberration',   id = 236, hex = 'D8BFD8' },
        { label = "It's Christmas",         id = 237, hex = 'FF0000' },
        { label = 'Temperature',            id = 238, hex = 'FFA07A' },
        { label = 'Yellow Orange Pearl',    id = 239, hex = 'FFAE42' },
        { label = 'Pink Blue Pearl',        id = 240, hex = 'D8BFD8' },
        { label = 'Green Blue Pearl',       id = 241, hex = '3CB371' },
        { label = 'Turquoise Black Pearl',  id = 242, hex = '00CED1' }
    },
}

if Config.ColorFavorites then
    Config.Paints.Favorites = { -- add your favorite custom colors here by hex
        { label = 'My Custom Paint Name!', hex = '' }
    }
end
